version: '3.8'

services:
  iphone-store:
    build: .
    ports:
      - '9002:9002'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=9002
      - HOSTNAME=0.0.0.0
    volumes:
      - ./.next:/app/.next
    restart: unless-stopped
