// Code generated by Slice Machine. DO NOT EDIT.
import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship['fields'][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship['id']]: ContentRelationshipFieldWithData<
      TSubRelationship['customtypes'],
      TLang
    >;
  } & { // Group
    [TGroup in Extract<
      TRelationship['fields'][number],
      prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup['id']]: TData[TGroup['id']] extends prismic.GroupField<infer TGroupData>
      ? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
      : never;
  } & { // Other fields
    [TFieldKey in Extract<TRelationship['fields'][number], string>]: TFieldKey extends keyof TData
      ? TData[TFieldKey]
      : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<TCustomType[number], string>['id']]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>['data'],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>['id']];

type PhoneDocumentDataSlicesSlice = PhoneSlice;

/**
 * Content for Phone documents
 */
interface PhoneDocumentData {
  /**
   * Slice Zone field in *Phone*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: phone.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PhoneDocumentDataSlicesSlice>;
}

/**
 * Phone document from Prismic
 *
 * - **API ID**: `phone`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PhoneDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<PhoneDocumentData>,
  'phone',
  Lang
>;

export type AllDocumentTypes = PhoneDocument;

/**
 * Primary content in *Phone → Default → Primary*
 */
export interface PhoneSliceDefaultPrimary {
  /**
   * Phone image field in *Phone → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: phone.default.primary.phone_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  phone_image: prismic.ImageField<never>;

  /**
   * Title field in *Phone → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title
   * - **API ID Path**: phone.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Small Desc field in *Phone → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Small desc
   * - **API ID Path**: phone.default.primary.small_desc
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  small_desc: prismic.KeyTextField;

  /**
   * Large desc field in *Phone → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Large desc
   * - **API ID Path**: phone.default.primary.large_desc
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  large_desc: prismic.RichTextField;

  /**
   * Price field in *Phone → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Price
   * - **API ID Path**: phone.default.primary.price
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  price: prismic.KeyTextField;

  /**
   * Color field in *Phone → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Color
   * - **API ID Path**: phone.default.primary.color
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  color: prismic.KeyTextField;

  /**
   * Capacity field in *Phone → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Capacity
   * - **API ID Path**: phone.default.primary.capacity
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  capacity: prismic.KeyTextField;
}

/**
 * Default variation for Phone Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PhoneSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<PhoneSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Phone*
 */
type PhoneSliceVariation = PhoneSliceDefault;

/**
 * Phone Shared Slice
 *
 * - **API ID**: `phone`
 * - **Description**: Phone
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PhoneSlice = prismic.SharedSlice<'phone', PhoneSliceVariation>;

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PhoneDocument,
      PhoneDocumentData,
      PhoneDocumentDataSlicesSlice,
      AllDocumentTypes,
      PhoneSlice,
      PhoneSliceDefaultPrimary,
      PhoneSliceVariation,
      PhoneSliceDefault,
    };
  }
}
