import type { Product } from './types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'iPhone 15 Pro',
    description: 'The ultimate iPhone.',
    price: 999,
    originalPrice: 1200,
    image: 'https://placehold.co/600x600/1e293b/FFFFFF.png',
    storage: '256GB',
    color: 'Natural Titanium',
    model: 'iPhone 15 Pro',
  },
  {
    id: '2',
    name: 'iPhone 15',
    description: 'A total powerhouse.',
    price: 799,
    originalPrice: 950,
    image: 'https://placehold.co/600x600/3b82f6/FFFFFF.png',
    storage: '128GB',
    color: 'Blue',
    model: 'iPhone 15',
  },
  {
    id: '3',
    name: 'iPhone 14',
    description: 'As amazing as ever.',
    price: 699,
    originalPrice: 850,
    image: 'https://placehold.co/600x600/a855f7/FFFFFF.png',
    storage: '128GB',
    color: 'Purple',
    model: 'iPhone 14',
  },
  {
    id: '4',
    name: 'iPhone SE',
    description: 'Serious power. Serious value.',
    price: 429,
    originalPrice: 550,
    image: 'https://placehold.co/600x600/f5f5f5/000000.png',
    storage: '64GB',
    color: 'Midnight',
    model: 'iPhone SE',
  },
  {
    id: '5',
    name: 'iPhone 15 Pro Max',
    description: 'The ultimate iPhone, but bigger.',
    price: 1199,
    originalPrice: 1400,
    image: 'https://placehold.co/600x600/737373/FFFFFF.png',
    storage: '512GB',
    color: 'White Titanium',
    model: 'iPhone 15 Pro Max',
  },
  {
    id: '6',
    name: 'iPhone 15 Plus',
    description: 'A total powerhouse, but bigger.',
    price: 899,
    originalPrice: 1100,
    image: 'https://placehold.co/600x600/4ade80/FFFFFF.png',
    storage: '256GB',
    color: 'Green',
    model: 'iPhone 15 Plus',
  },
];
